### ISSUE TITLE
regression.py yields KeyError: '?gene'

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-owl-tools#13]
Using the state of the `regression.py` script in `master`, running the script in the following invocation results in a `KeyError: '?gene'` error:

```bash
Reigen:src (master) $ python regression.py 659
Traceback (most recent call last):
  File "regression.py", line 173, in <module>
    main()
  File "regression.py", line 7, in main
    get_scores()
  File "regression.py", line 41, in get_scores
    query_parse_results(size)
  File "regression.py", line 90, in query_parse_results
    scorefile.write(gene+"\t"+str(size[gene])+"\t"+genename+"\t"+taxon+"\t"+str(size[taxon])+"\t"+taxonname+"\t"+str(score)+"\t"+uri+ "\n")
KeyError: '?gene'
```

Here are the top lines of the two files the scripts reads from `../results/`:
```bash
Reigen:src (master) $ head -n 10 ../results/ProfileSizes.txt ../results/Scores_Gene_Taxon.tsv 
==> ../results/ProfileSizes.txt <==
http://zfin.org/ZDB-GENE-090303-6#profile	13
http://www.informatics.jax.org/marker/MGI:99782#profile	13
http://zfin.org/ZDB-GENE-061215-5#profile	3
http://purl.obolibrary.org/obo/VTO_0058013#profile	35
http://www.informatics.jax.org/marker/MGI:2153041#profile	6
http://www.informatics.jax.org/marker/MGI:2429765#profile	19
http://www.informatics.jax.org/marker/MGI:1353568#profile	14
http://www.informatics.jax.org/marker/MGI:97253#profile	17
http://zfin.org/ZDB-GENE-070117-318#profile	3
http://www.informatics.jax.org/marker/MGI:96616#profile	14

==> ../results/Scores_Gene_Taxon.tsv <==
?match	?score	?gene	?genename	?taxon	?taxonname
<http://purl.org/phenoscape/uuid/b1ebb22c-3c8d-4dd4-8ba3-ccaaabe39742>	"0.2403294258323937"^^<http://www.w3.org/2001/XMLSchema#double>	<http://www.informatics.jax.org/marker/MGI:1336991>	"Trp73"^^<http://www.w3.org/2001/XMLSchema#string>	<http://purl.obolibrary.org/obo/VTO_0000007>	"Vertebrata"^^<http://www.w3.org/2001/XMLSchema#string>
<http://purl.org/phenoscape/uuid/a5b881f4-2418-48d9-9c40-13d14df0f156>	"0.26763896100146445"^^<http://www.w3.org/2001/XMLSchema#double>	<http://www.informatics.jax.org/marker/MGI:1336991>	"Trp73"^^<http://www.w3.org/2001/XMLSchema#string>	<http://purl.obolibrary.org/obo/VTO_0000008>	"Gnathostomata"^^<http://www.w3.org/2001/XMLSchema#string>
<http://purl.org/phenoscape/uuid/af31b5b3-63eb-4c53-a1e6-febd3d9ea9e5>	"0.4355696053521025"^^<http://www.w3.org/2001/XMLSchema#double>	<http://www.informatics.jax.org/marker/MGI:1336991>	"Trp73"^^<http://www.w3.org/2001/XMLSchema#string>	<http://purl.obolibrary.org/obo/VTO_0000009>	"Chondrichthyes"^^<http://www.w3.org/2001/XMLSchema#string>
<http://purl.org/phenoscape/uuid/b7135519-8c05-4d88-8ddd-675a9bb59671>	"0.13913321833371048"^^<http://www.w3.org/2001/XMLSchema#double>	<http://www.informatics.jax.org/marker/MGI:1336991>	"Trp73"^^<http://www.w3.org/2001/XMLSchema#string>	<http://purl.obolibrary.org/obo/VTO_0000061>	"Elasmobranchii"^^<http://www.w3.org/2001/XMLSchema#string>
<http://purl.org/phenoscape/uuid/a6850ba5-f5b8-40f1-9bcd-cf201bdd7b36>	"0.07519540146398669"^^<http://www.w3.org/2001/XMLSchema#double>	<http://www.informatics.jax.org/marker/MGI:1336991>	"Trp73"^^<http://www.w3.org/2001/XMLSchema#string>	<http://purl.obolibrary.org/obo/VTO_0002413>	"Rhinophrynidae"^^<http://www.w3.org/2001/XMLSchema#string>
<http://purl.org/phenoscape/uuid/bd9a4d37-e24e-49c2-8f85-b12e2a62da47>	"0.09315132586350311"^^<http://www.w3.org/2001/XMLSchema#double>	<http://www.informatics.jax.org/marker/MGI:1336991>	"Trp73"^^<http://www.w3.org/2001/XMLSchema#string>	<http://purl.obolibrary.org/obo/VTO_0002644>	"Scaphiopus"^^<http://www.w3.org/2001/XMLSchema#string>
<http://purl.org/phenoscape/uuid/bbc0138e-3d22-4055-8417-b84cd8ca7150>	"0.12124088411148491"^^<http://www.w3.org/2001/XMLSchema#double>	<http://www.informatics.jax.org/marker/MGI:1336991>	"Trp73"^^<http://www.w3.org/2001/XMLSchema#string>	<http://purl.obolibrary.org/obo/VTO_0002674>	"Ceratobatrachidae"^^<http://www.w3.org/2001/XMLSchema#string>
<http://purl.org/phenoscape/uuid/a5df50e4-124e-41d5-a2f3-58e5bd33722f>	"0.13408715748853178"^^<http://www.w3.org/2001/XMLSchema#double>	<http://www.informatics.jax.org/marker/MGI:1336991>	"Trp73"^^<http://www.w3.org/2001/XMLSchema#string>	<http://purl.obolibrary.org/obo/VTO_0003069>	"Dicroglossinae"^^<http://www.w3.org/2001/XMLSchema#string>
<http://purl.org/phenoscape/uuid/abd35cb5-a892-41bc-91ea-8d77704f836a>	"0.11251083385556307"^^<http://www.w3.org/2001/XMLSchema#double>	<http://www.informatics.jax.org/marker/MGI:1336991>	"Trp73"^^<http://www.w3.org/2001/XMLSchema#string>	<http://purl.obolibrary.org/obo/VTO_0003566>	"Rhacophorinae"^^<http://www.w3.org/2001/XMLSchema#string>
```

It looks like we aren't in a position yet to run this Python script reproducibly. @prashanti can you comment what might be going wrong here?

**Comment by hlapp** [comment]
Just in case it helps or matters, here's the version information for Python and Numpy I'm trying to run this with:

```bash
Reigen:src (master) $ python
Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import numpy
>>> print numpy.__version__
1.9.2
>>>
```

**Comment by balhoff** [comment]
Sorry! This is due to independent SPARQL queries used by me and Prashanti to get the input data. Please try after commit f0c04f5ccbf7ac1aa41c8fa94d3ada11f715cf62.

**Comment by hlapp** [comment]
OK this works now. Thanks!

**Comment by prashanti** [comment]
The column header for the data returned by the SPARQL query seems to have
changed causing the issue. Jim's commit above should fix the error.

On Fri, Oct 16, 2015 at 1:02 PM, Jim Balhoff <notifications@github.com>
wrote:

> Sorry! This is due to independent SPARQL queries used by me and Prashanti
> to get the input data. Please try after commit f0c04f5
> <https://github.com/phenoscape/phenoscape-owl-tools/commit/f0c04f5ccbf7ac1aa41c8fa94d3ada11f715cf62>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phenoscape/phenoscape-owl-tools/issues/13#issuecomment-148787038>
> .
>



-- 
Prashanti Manda, Ph.D.
Postdoctoral Research Associate
Department of Biology
University of North Carolina, Chapel Hill
http://orcid.org/0000-0002-7162-7770
